export const availableTemplates = [
    "badge",
    "blank",
    "card",
    "checkbox",
    "dialog",
    "disclosure",
    "divider",
    "flipper",
    "number-field",
    "progress",
    "progress-ring",
    "search",
    "switch",
    "text-field",
]